name: Create Automatic Release

on:
  workflow_dispatch:

jobs:
  create-jetbrains-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get version from gradle.properties
        id: get_version
        run: |
          version=$(grep '^pluginVersion=' extensions/intellij/gradle.properties | cut -d'=' -f2)
          new_version="v${version}-jetbrains"
          echo "New version will be: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$NEW_VERSION" \
            --generate-notes \
            --title "$NEW_VERSION" \
            --draft \
            --latest \
            --prerelease
